version: "2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: "bitnami/mongodb:4.0"
    ports:
      - "27017:27017"
